# Fly.io configuration file
app = "showtime"  # Your app name
primary_region = "sea"  # Seattle region

[build]
  # Use the production Dockerfile in the root directory
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[services.ports]]
  port = 443
  handlers = ["http"]
  [services.ports.http_options]
    response.headers.X-Frame-Options = "SAMEORIGIN"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512